#ifndef CHANNELINFO_h
#define CHANNELINFO_h



#define NUM_ADC_CHANNELS 40

#define BGO_CHANNELS 24
#define BGO_ADC_START_CHANNEL 0
#define BGO_ADC_END_CHANNEL 7

#define CEF3_CHANNELS 4
#define CEF3_ADC_START_CHANNEL 2
#define CEF3_ADC_END_CHANNEL 5

#define HODOSMALLX_ADC_BOARD 1
#define HODOSMALLX_CHANNELS 8
#define HODOSMALLX_ADC_START_CHANNEL 16
#define HODOSMALLX_ADC_END_CHANNEL 23

#define HODOSMALLY_ADC_BOARD 1
#define HODOSMALLY_CHANNELS 8
#define HODOSMALLY_ADC_START_CHANNEL 24
#define HODOSMALLY_ADC_END_CHANNEL 31

#define HODOX1_ADC_BOARD 1
#define HODOX1_CHANNELS 8
#define HODOX1_ADC_START_CHANNEL 16
#define HODOX1_ADC_END_CHANNEL 23

#define HODOY1_ADC_BOARD 1
#define HODOY1_CHANNELS 8
#define HODOY1_ADC_START_CHANNEL 24
#define HODOY1_ADC_END_CHANNEL 31

#define HODOX2_ADC_BOARD 1
#define HODOX2_CHANNELS 8
#define HODOX2_ADC_START_CHANNEL 16
#define HODOX2_ADC_END_CHANNEL 23

#define HODOY2_ADC_BOARD 1
#define HODOY2_CHANNELS 8
#define HODOY2_ADC_START_CHANNEL 24
#define HODOY2_ADC_END_CHANNEL 31

#define S1_ADC_BOARD 1
#define S1_ADC_CHANNEL 0

#define S3_ADC_BOARD 1
#define S3_ADC_CHANNEL 0

#define S4_ADC_BOARD 1
#define S4_ADC_CHANNEL 0

#define S6_ADC_BOARD 1
#define S6_ADC_CHANNEL 0


#endif 
