#ifndef CHANNELINFO_h
#define CHANNELINFO_h

#define BGO_CHANNELS 24
#define BGO_ADC_START_CHANNEL 0

#define S1_ADC_CHANNELS 1
#define S1_ADC_START_CHANNEL 24

#define S3_ADC_CHANNELS 1
#define S3_ADC_START_CHANNEL 25

#define S4_ADC_CHANNELS 1
#define S4_ADC_START_CHANNEL 26

#define S6_ADC_CHANNELS 1
#define S6_ADC_START_CHANNEL 27

#define WC_X_ADC_CHANNELS 1
#define WC_X_ADC_START_CHANNEL 28

#define WC_Y_ADC_CHANNELS 1
#define WC_Y_ADC_START_CHANNEL 29

#define HODOX1_CHANNELS 64
#define HODOX1_ADC_START_CHANNEL 30

#define HODOY1_CHANNELS 64
#define HODOY1_ADC_START_CHANNEL 94

#define HODOX2_CHANNELS 64
#define HODOX2_ADC_START_CHANNEL 158

#define HODOY2_CHANNELS 64
#define HODOY2_ADC_START_CHANNEL 222

#define HODOSMALLX_CHANNELS 8
#define HODOSMALLX_ADC_START_CHANNEL 286

#define HODOSMALLY_CHANNELS 8
#define HODOSMALLY_ADC_START_CHANNEL 294


#define CEF3_CHANNELS 4
#define CEF3_START_CHANNEL 0


#endif 
